/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.FactoryDao;
import dao.IDaoGeneral;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import pojo.PojoProfessor;

/**
 *
 * @author asunawesker
 */
public class ProfessorSearch extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProfessorSearch
     */
    
    PojoProfessor professor;
    IDaoGeneral<PojoProfessor, String> dao;
    List<PojoProfessor> ls;
    
    public ProfessorSearch() throws SQLException {
        initComponents();
        this.professor = new PojoProfessor();
        this.dao = FactoryDao.create(FactoryDao.TypeDAO.PROFESSOR);
        this.ls = dao.readAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnVerUno = new javax.swing.JButton();
        btnVerTodos = new javax.swing.JButton();

        setClosable(true);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("ID");

        btnVerUno.setText("Ver uno");
        btnVerUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerUnoActionPerformed(evt);
            }
        });

        btnVerTodos.setText("Ver todos");
        btnVerTodos.setDefaultCapable(false);
        btnVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel8)
                .addGap(24, 24, 24)
                .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnVerUno)
                .addGap(52, 52, 52)
                .addComponent(btnVerTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerUno)
                    .addComponent(btnVerTodos))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerUnoActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText();
                
        try {
            PojoProfessor e;
            e = dao.readSingle(id);
            System.out.println(
                "\nMatrícula: " + e.getIdCard()+
                "\nNombre: "  + e.getName()+
                "\nApellido: "  + e.getLastName()+
                "\nCarrera: "   + e.getCareer()+
                "\n"
            );
        } catch (SQLException ex) {
            Logger.getLogger(ProfessorSearch.class.getName()).log(Level.SEVERE, null, ex);
        }            
    }//GEN-LAST:event_btnVerUnoActionPerformed

    private void btnVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodosActionPerformed
        // TODO add your handling code here:
        ls.clear();
        
        try {
            ls = dao.readAll();
            
            ls.forEach((professor) -> {
                System.out.println(
                    "\nMatrícula: " + professor.getIdCard()+
                    "\nNombre: "  + professor.getName()+
                    "\nApellido: "  + professor.getLastName()+
                    "\nCarrera: "   + professor.getCareer()+
                    "\n"
                );
                
            }); 
            
        } catch (SQLException ex) {
            Logger.getLogger(ProfessorSearch.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_btnVerTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerTodos;
    private javax.swing.JButton btnVerUno;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
