/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.FactoryDao;
import dao.IDaoGeneral;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import pojo.PojoStudent;

/**
 *
 * @author asunawesker
 */
public class StudentSearch extends javax.swing.JInternalFrame {

    /**
     * Creates new form StudentSearch
     */
    
    PojoStudent student;
    IDaoGeneral<PojoStudent, String> dao;
    List<PojoStudent> ls;
    
    public StudentSearch() throws SQLException {
        this.student = new PojoStudent();
        this.dao = FactoryDao.create(FactoryDao.TypeDAO.STUDENT);
        this.ls = dao.readAll();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnVerUno = new javax.swing.JButton();
        btnVerTodos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setClosable(true);
        setTitle("Buscar estudiante");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Matricula");

        btnVerUno.setText("Ver uno");
        btnVerUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerUnoActionPerformed(evt);
            }
        });

        btnVerTodos.setText("Ver todos");
        btnVerTodos.setDefaultCapable(false);
        btnVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodosActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matrícula", "Nombre", "Apellido", "Carrera"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnVerUno)
                        .addGap(51, 51, 51)
                        .addComponent(btnVerTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerUno)
                    .addComponent(btnVerTodos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerUnoActionPerformed
        ls.clear();
        try {
            String id = txtId.getText();            
            PojoStudent e = dao.readSingle(id);
            ls.add(e);
//            System.out.println(
//                    "\nMatrícula: " + e.getEnrollment()+
//                            "\nNombre: "  + e.getName()+
//                            "\nApellido: "  + e.getLastName()+
//                            "\nCarrera: "   + e.getCareer()+
//                            "\n"
//            );
            showTable(ls);
        } catch (SQLException ex) {
            Logger.getLogger(StudentSearch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerUnoActionPerformed

    private void btnVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodosActionPerformed
        // TODO add your handling code here:
        ls.clear();
        
        try {
            ls = dao.readAll();            
//            ls.forEach((student) -> {
//                System.out.println(
//                    "\nMatrícula: " + student.getEnrollment()+
//                    "\nNombre: "  + student.getName()+
//                    "\nApellido: "  + student.getLastName()+
//                    "\nCarrera: "   + student.getCareer()+
//                    "\n"
//                );
//                
//            }); 
            showTable(ls);            
        } catch (SQLException ex) {
            Logger.getLogger(StudentSearch.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_btnVerTodosActionPerformed

    private void showTable(List<PojoStudent> ls){
        Object matrix [][] = new Object[ls.size()][4];
        
        for (int i = 0; i < ls.size(); i++) {
            matrix [i][0] = ls.get(i).getEnrollment();
            matrix [i][1] = ls.get(i).getName();
            matrix [i][2] = ls.get(i).getLastName();
            matrix [i][3] = ls.get(i).getCareer();
        }
        
         table.setModel(new javax.swing.table.DefaultTableModel(
            matrix,
            new String [] {
                "ID", "Nombre", "Apellido", "Carrera"
            }
        ));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerTodos;
    private javax.swing.JButton btnVerUno;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
